language: python

python:
  - 2.7
  - 3.5

matrix:
  allow_failures:
    - python: 3.5

before_script:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter

script:
  - python setup.py test

after_success:
  - codeclimate-test-reporter